spring.application.name=SpringEcom
spring.datasource.url=jdbc:mysql://localhost:3306/SpringBootMvcProject
spring.datasource.username=root
spring.datasource.password=niTin@8821
spring.jpa.hibernate.ddl-auto=update
spring.dataSource.hikari.auto-commit=false
